In [4]:
 # Dependencies
import pandas as pd
import numpy as np
import requests
import json

# Google API Key
from config import gkey

In [5]:
 # Import cities file as DataFrame
cities_pd = pd.read_csv("../Raw_Data/cities.csv")
cities_pd

             City
0     Los Angeles
1      Long Beach
2   Santa Clarita
3        Glendale
4        Palmdale
5       Lancaster
6          Pomona
7        Torrance
8        Pasadena
9       Inglewood
10       El Monte
11         Downey
12    West Covina
13        Norwalk
14        Burbank
15        Compton
16     South Gate
17       Whittier
18      Hawthrone
19       Alhambra

In [6]:
# Add columns for lat, lng, airport name, airport address, airport rating
# Note that we used "" to specify initial entry.
cities_pd["Lat"] = ""
cities_pd["Lng"] = ""
cities_pd["Zip Code"] = ""
cities_pd["Population"] = ""
cities_pd.head()

            City Lat Lng Zip Code Population
0    Los Angeles
1     Long Beach
2  Santa Clarita
3       Glendale
4       Palmdale

In [14]:
 # create a params dict that will be updated with new city each iteration
params = {"key": gkey}

# Loop through the cities_pd and run a lat/long search for each city
for index, row in cities_pd.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"

    city = row['City']
    

    # update address key value
    params['address'] = f"{city}"

    # make request, print url
    cities_lat_lng = requests.get(base_url, params=params)
    print(cities_lat_lng.url)
    # convert to json
    cities_lat_lng = cities_lat_lng.json()

    cities_pd.set_value(
        index, "Lat", cities_lat_lng["results"][0]["geometry"]["location"]["lat"])
    cities_pd.set_value(
        index, "Lng", cities_lat_lng["results"][0]["geometry"]["location"]["lng"])

# Visualize to confirm lat lng appear
cities_pd.head()

https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Los+Angeles
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Long+Beach
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Santa+Clarita
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Glendale
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Palmdale
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Lancaster
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Pomona
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Torrance
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Pasadena
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Inglewood
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=El+Monte
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Downey
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=West+Covina
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Norwalk
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Burbank
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Compton
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=South+Gate
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Whittier
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Hawthrone
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyDriWVOHE4AoyPpVFnvU04MSSANGKeAM_4&address=Alhambra

            City      Lat      Lng Zip Code Population
0    Los Angeles  34.0522 -118.244
1     Long Beach  33.7701 -118.194
2  Santa Clarita  34.3917 -118.543
3       Glendale  34.1425 -118.255
4       Palmdale  34.5794 -118.116

In [15]:
# Save Data to csv
cities_pd.to_csv("CitiesGeo_Output.csv")

# Visualize to confirm airport data appears
cities_pd.head(10)

            City      Lat      Lng Zip Code Population
0    Los Angeles  34.0522 -118.244
1     Long Beach  33.7701 -118.194
2  Santa Clarita  34.3917 -118.543
3       Glendale  34.1425 -118.255
4       Palmdale  34.5794 -118.116
5      Lancaster  40.0379 -76.3055
6         Pomona  34.0551  -117.75
7       Torrance  33.8358 -118.341
8       Pasadena  34.1478 -118.145
9      Inglewood  33.9617 -118.353